### ISSUE TITLE
Error: Aborted because ... is not accepted

### ISSUE THREAD

**Issue by sahanarula** [webpack-contrib/grunt-webpack#132]
The app is not accepting the update and throws a warning `Error: Aborted because ... is not accepted`

webpack.config
```json
module.exports = {
  "entry": ["whatwg-fetch", "babel-polyfill", "./app/app.js"],

  "stats": {
      "colors": false,
      "modules": true,
      "reasons": true
  },

  "failOnError": true, 

  "resolve": {
    "extensions": ['.js', '.jsx', '.json']
  },

  "module": {
    "loaders": [
      {
        "test": /\.jsx?$/,
        "exclude": /node_modules/,
        "loaders": ["babel-loader"]
      }
    ]
  },
}

```

grunt config 
```json
  {
      "webpack": _.extend(_.clone(webpackConfig), {
        "output": {
            "path": __dirname,
            "filename": "abc.js",
            "publicPath": "http://localhost:8080/",
        }
      }),

      "contentBase": __dirname + "/../../app",
      "filename": "abc.js",
      "inline": true,
      "hot": true,
    }
```

### Expected Behavior
The app should update only selective components based on the HMR update.

### Current Behavior
It reloads after throwing the above mentioned warning.

### Your Environment

| software         | version
| ---------------- | -------
| webpack          | 2.2.1
| grunt-webpack    | 3.0.0-beta.1
| grunt            | 1.0.1
| node             | 4.3.0
| npm              | 2.14.12
| Operating System | macOS Sierra

**Comment by danez** [comment]
Can you try if this is fixed with 3.0.0-beta.1 ?

**Comment by sahanarula** [comment]
I already tried it with `3.0.0-beta.1`

**Comment by danez** [comment]
Ok I digged into this problem a little bit and was able to reproduce this, but not only with grunt-webpack, but also with webpack-dev-server itself.
Depending on how you use hot reloading you need to modify your entrypoint and add
```js
if (module.hot)
  module.hot.accept()
```
From: https://github.com/webpack/webpack-dev-server/issues/395#issuecomment-198532974

Let me know if that helps.

**Comment by danez** [comment]
Closing for now, please reopen if you can reproduce with grunt-webpack but not with webpack-dev-server cli.
