### ISSUE TITLE
Can't seem to use Promises for grunt-webpack configuration

### ISSUE THREAD

**Issue by ngyikp** [webpack-contrib/grunt-webpack#136]
### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)
Gruntfile.js:
```js
'use strict';

module.exports = (grunt) => {
	grunt.loadNpmTasks('grunt-webpack');

	grunt.initConfig({
		webpack: {
			options: {
				progress: true
			},
			app: require('./webpack.config')()
		},
	});
};
```

webpack.config.js:
```js
'use strict';

module.exports = () => {
	return new Promise((resolve, reject) => {
		// some async stuff to do...

		resolve({
			entry: './app.js',
			output: {
				filename: 'out.js'
			}
		});
	})
};
```

### Expected Behavior
It should work.

### Current Behavior
```
$ grunt webpack
Running "webpack" task
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration misses the property 'entry'.
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation. Use --force to continue.

Aborted due to warnings.
```

### Possible Solution
https://github.com/webpack-contrib/grunt-webpack/blob/0d81d9f05d3714c555c89450485c72f0fa1c7566/src/options/default.js#L54

<img width="857" alt="screen shot 2017-04-16 at 12 09 02 pm" src="https://cloud.githubusercontent.com/assets/6135313/25068656/94c817b0-229d-11e7-9e67-d81b70418e92.png">

Seems that part of the problem is it's trying to merge the `targetOptions` Promise with everything else.

### Context
webpack allows [configurations to be made with Promises](https://webpack.js.org/configuration/configuration-types/#exporting-a-promise), but it seems that it is not possible to integrate it with grunt-webpack.

My workaround is to process the Promises myself and put it into the Grunt config later.

### Your Environment
| software         | version
| ---------------- | -------
| webpack          | 2.4.1
| grunt-webpack    | 3.0.0-beta.2
| grunt            | 1.0.1
| node             | 7.9.0
| npm              | 4.5.0
| Operating System | macOS 10.12.4

**Comment by danez** [comment]
Ok so probably if it is a Promise, the grunt plugin should wait till the promise resolves and then start webpack.
I'm out of town but will try to have a look next week.
