### ISSUE TITLE
Cannot define multiple webpack-dev-server task

### ISSUE THREAD

**Issue by steveetm** [webpack-contrib/grunt-webpack#139]
### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)
gruntfile.js
```js
    "webpack-dev-server": {
        frontend: {
            options: {
                webpack: webpackConfig.frontend,
                publicPath: '/',
                hot: true,
                compress: true,
                port: 9000,
                contentBase: path.resolve(process.cwd(), 'build/www/'),
            },
            start: {
                webpack: {
                    devtool: "cheap-eval-sourcemap"
                }
            }
        },
        backend: {
            options: {
                webpack: webpackConfig.backend,
                publicPath: '/',
                hot: true,
                compress: true,
                port: 9000,
                contentBase: path.resolve(process.cwd(), 'build/www/'),
            },
            start: {
                webpack: {
                    devtool: "cheap-eval-sourcemap"
                }
            }
        }

    }
```
webpack.config.js
```js
module.exports = {
    frontend: {
        resolve: {
            modules: [process.cwd(), 'client/', 'client/app/', 'node_modules']
        },
        entry: {
            'client': './client/app/app.js',
        },
        output: {
            path: path.resolve(process.cwd(), 'build/www'),
            filename: "client-[name].entry.js"
        },
        module: {
            rules: [
                {
                    test: /\.js/,
                    exclude: /node_modules/,
                    use: [
                        {
                            loader: 'babel-loader',
                            options: {
                                presets: ['babel-preset-es2015'],
                                plugins: ["transform-remove-strict-mode"],
                                ignore: ['client/vendor/sdk/ext']

                            },
                        }
                    ]
                }
            ],
        },
    }
};
```
### Expected Behavior
grunt webpack-dev-server:frontend
grunt webpack-dev-server:backend
Both should work

### Current Behavior
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an object.
    * configuration.entry should be a string.
    * configuration.entry[1] should be a string.
    * configuration.entry should be an instance of function
      function returning an entry object or a promise.. Use --force to continue.

### Your Environment

| software         | version
| ---------------- | -------
| webpack          |  2.3.3-2.5.1
| grunt-webpack    | 3.0.0
| grunt            | 1.0.1
| node             | 6.10.1
| npm              | 3.10.10
| Operating System |  OSX 10.12.4

**Comment by danez** [comment]
The configuration should be or similar. If your external webpack config does not define devtool, you can also move the devtool option to `options`.
```js
    "webpack-dev-server": {
        options: {
            publicPath: '/',
            hot: true,
            compress: true,
            port: 9000,
            contentBase: path.resolve(process.cwd(), 'build/www/'),
        },
        frontend: {
            webpack: {
                ...webpackConfig.frontend,
                devtool: "cheap-eval-sourcemap"
            }
        },
        backend: {
            webpack: {
                ...webpackConfig.backend,
                devtool: "cheap-eval-sourcemap"
            }
        }
    }
```

**Comment by steveetm** [comment]
Hey,

While this probably perfectly fine for my example, so indeed my original config was flawed, I don't think I can accept it as a solution. So what should I do when I want to run frontend on port 9000 and backend on port 9001, as I think this is also a valid use-case.

Our current workaround/solution is that the `let webpackConfig = require('./webpack.config.js')` returns a function which can accept a config object as argument and here is the grunt config:

```js
'webpack-dev-server': {
                options: {
                    webpack: webpackConfig(options.config).configObj,
                    publicPath: '/',
                    hot: options.config.hot || true,
                    compress: options.config.compress || true,
                    port: options.config.port || 9000,
                    contentBase: path.resolve(process.cwd(), `build/app/${options.config.app}/www/`),
                },
                start: {
                    webpack: {
                        devtool: 'cheap-eval-source-map',
                    },
                },
            },
```

And by this way you can use 
```shell
grunt webpack-dev-server --app=frontend --port 9001
grunt webpack-dev-server --app=backend --port 9002
```

I know this is also a bit different but IMO it should be possible to define totally different subtasks under webpack-dev-server. Also docs could definietly help there:)

**Comment by choule99** [comment]
I might also add that the grunt webpack-dev-server task is really badly documented. I've been pouring over the code to make sense out of it, and I just gave up.

I wrapped the webpack-dev-server inside a grunt-shell task instead.

**Comment by jbasrai** [comment]
I don't think the documentation is clear at all for using `webpack-dev-server`. I didn't know the shape of the config object had to be `{ webpack-dev-server:  { <taskName>: { webpack: <config> }}}`.

**Comment by DmitryGonchar** [comment]
@danez 
```
'webpack-dev-server': {
    options: { ...  },
    dev: {
        webpack: Object.assign({}, webpackDevConfig);
    }
```
returns same error ("configuration.entry should be one of these:")
