### ISSUE TITLE
grunt-webpack doesn't work with next version of webpack-dev-server 3.x.x

### ISSUE THREAD

**Issue by gejgalis** [webpack-contrib/grunt-webpack#158]
### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

```json
any
```

### Expected Behavior
`grunt-webpack` should work with next version of `webpack-dev-server@3.x.x`

### Current Behavior
Doesn't work. Webpack Dev Server has changed API since 3.x.x

### Your Environment

| software         | version
| ---------------- | -------
| webpack          |  3.10.0
| webpack-dev-server | 3.0.0-alpha6
| grunt-webpack    |  3.0.2
| grunt            | 1.0.1
| node             | 8.9.3
| npm              | 3.10.10
| Operating System | Windows

**Comment by danez** [comment]
Thanks for letting me know, will look into this now.

**Comment by danez** [comment]
Can you please explain more what is not working or add an error message. It looks to me that dev-server 3.x just works fine with the latest version of `grunt-webpack`

**Comment by gejgalis** [comment]
It seems with newest webpack-dev-server it is working now. I'm closing this issue.
