### ISSUE TITLE
webpack.BannerPlugin improperly evaluated since upgrading to Webpack 4

### ISSUE THREAD

**Issue by jlchereau** [webpack-contrib/grunt-webpack#163]
My gruntfile.js has always been configured (prior to webpack 3) to add a banner to webpack bundles including copyright and version read from package.json.

```js
const webpack = require('webpack');
const webpackConfig = require('./webpack.config.js');
...
grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    ...
    webpack: {
        // @see https://github.com/webpack/webpack-with-common-libs/blob/master/Gruntfile.js
        options: webpackConfig,
        build: {
            cache: false,
            devtool: false,
            plugins: webpackConfig.plugins.concat(
                new webpack.BannerPlugin({
                    banner:
                        '/*! <%= pkg.copyright %> - Version <%= pkg.version %> dated <%= grunt.template.today() %> */',
                    raw: true
                    // entryOnly: true
                })
            )
        }
    } 
}
```

### Expected Behavior

With webpack 3, the following banner is added **after** evaluating pkg.copyright, pkg.version, ...:

```
/*! Copyright ©2013-2018. All rights reserved. - Version 0.3.8 dated Wed Jun 06 2018 09:02:04 */
```
### Current Behavior

Since upgrading to webpack 4, the following banner is added **without** evaluating pkg.copyright, pkg.version, ..:

```
/*! <%= pkg.copyright %> - Version <%= pkg.version %> dated <%= grunt.template.today() %> */
```

Since upgrading to webpack 4, grunt-webpack no more evaluates the banner prior to passing it to webpack.BannerPlugin.

### Your Environment
| software         | version
| ---------------- | -------
| webpack          |  4.11.1
| grunt-webpack    | 3.1.2
| grunt            | 1.0.3
| node             | 10.3.0
| npm              | 6.1.0
| Operating System | Windows 10 with latest updates

**Comment by jlchereau** [comment]
Please note that there is no issue in package.json because gruntfile.js also has the following that produces the correct banner:

```js
uglify: {
    build: {
        options: {
            banner:
                '/*! <%= pkg.copyright %> - Version <%= pkg.version %> dated <%= grunt.template.today() %> */',
            sourceMap: false
        },
        files: {
            'webapp/public/build/workerlib.bundle.js': [
                'js/workerlib.js'
            ]
        }
    }
},
```

**Comment by danez** [comment]
I created a fix that will fix this problem.

**Comment by jlchereau** [comment]
Fixed. Thx.
