### ISSUE TITLE
SplitChunks cacheGroups test callback function does not work with grunt webpack

### ISSUE THREAD

**Issue by scssyworks** [webpack-contrib/grunt-webpack#169]
### Summary
Webpack 4 officially supports ``SplitChunks`` plugin which has a ``cacheGroups`` property which allows us to logically group chunks. It accepts a ``test`` parameter which can either be a string, a JavaScipt regular expression or a function. The JS regular expression works as expected, but when using a function it fails with grunt webpack which otherwise works fine.

### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

Grunt config:
```js
{
  webpack: {
    options: {
      stats: !process.env.NODE_ENV || process.env.NODE_ENV === 'development'
    },
    prod: require('../webpack.config'),
    dev: require('../webpack.dev')
  }
}
```

Parts of webpack.config
```js
{
  optimization: {
    splitChunks: {
      cacheGroups: {
        common: {
          test: function (module) {
            if (module.resource) {
              return module.resource.includes('path/to/file');
            }
          },
          name: 'common',
          minSize: 0,
          chunks: 'all'
        }
      }
    }
  }
}
```

### Expected Behavior
Test function as shown above should work with grunt webpack

### Current Behavior
Test function is completely ignored by grunt webpack resulting into random chunks getting generated

### Context
I am using webpack for JavaScript and SCSS compilation and bundling, and grunt to deploy code to local server. I wanted to implement watch on webpack and grunt both in development mode, hence thought of using grunt webpack plugin in order to configure watch at one place. Since logical grouping of chunks have stopped working with grunt webpack, I am not able to use it.

### Your Environment

| software         | version
| ---------------- | -------
| webpack          | 4.29.0
| grunt-webpack    | 3.1.3
| grunt            | 0.4.5
| node             | 10.15.0
| npm              | 6.4.1
| Operating System | MAC OS High Sierra

**Comment by danez** [comment]
Thanks for reporting. I will have a look at it.

**Comment by oatw** [comment]
@scssyworks Add `enforce: true` solved the problem in my case. I dived into the plugin source code and found that chunks are bundled into standalone files depending on multiple params. I guess the `enforce` param is to ignore others. So try it, I guess it will work in most cases.
[source code link](https://github.com/webpack/webpack/blob/b41e2c68a5d707bd2d315b7b10f6b714c78f0474/lib/optimize/SplitChunksPlugin.js#L267)

**Comment by danez** [comment]
I can confirm it works as expected. Added a testcase: https://github.com/webpack-contrib/grunt-webpack/blob/438589bb13ac4ac442bfa84dc6265220265ae131/tests/integration/fixtures/webpack/split-chunks-issue-169/Gruntfile.js
