### ISSUE TITLE
hangs in the docker container in Jenkins pipeline

### ISSUE THREAD

**Issue by sativ01** [webpack-contrib/grunt-webpack#175]
Webpack runs fine on my machine but gets stuck on the Docker container in CI/CD pipeline.
I have replaced grunt-webpack call in Grunfile to do webpack build using shell command and it went fine on the docker.
It gets stuck eternally, it is only possible to stop it by aborting the build
the last webpack output is:
`Running "webpack:dist" (webpack) task`

### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

Gruntfile.js
```js
{
...
     webpack: {
      options: {
       progress: true,
       keepalive: false,
      },
      dist: webPackDistConfig,
      dev: webPackDevConfig,
    },
}
...
grunt.loadNpmTasks('grunt-webpack');
```

### Expected Behavior
Should complete the build

### Current Behavior
Build hangs on webpack step

### Possible Solution
using **grunt-shell** to run the task with npm command to build webpack

### Context
Running the grunt-webpack task in the docker in CI/CD pipeline

### Your Environment

| software         | version
| ---------------- | -------
| webpack          | 4.30.0
| grunt-webpack    | 3.1.3
| grunt            | 1.0.4
| node             | 8.9.4
| npm              | 5.6.0
| Operating System | Windows 10

**Comment by danez** [comment]
There is not enough information here, not sure why it would hang.
