### ISSUE TITLE
webpack 5 deprecation warning 

### ISSUE THREAD

**Issue by adaamz** [webpack-contrib/grunt-webpack#188]
### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)
Gruntfile.js:
```js
module.exports = function(grunt) {
    grunt.loadNpmTasks('grunt-webpack');

    const webpackPanelConfig = require('webpack.config.js');
    grunt.initConfig({
        webpack: {
            panel: webpackPanelConfig("production"),
            panel_watch: webpackPanelConfig("development"),
        }
    }); // removed unrelated grunt tasks
}
```
webpack.config.js
```js
const config = {
    entry: "App.ts",
}; // simplified

module.exports = function(env) {
    return config; //simplified
};
```

### Expected Behavior
No deprecation warnings :)

### Current Behavior
```
> grunt ts:watch
Running "webpack:panel_watch" (webpack) task
10% building(node:19988) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the '
watch' option without a callback.
```

### Context
Trying to update webpack from 4 to 5.

### Your Environment
btw this command `npm ls grunt webpack grunt-webpack` gives me error
```
+-- grunt@1.3.0
+-- grunt-webpack@4.0.2
`-- UNMET PEER DEPENDENCY webpack@5.2.0

npm ERR! peer dep missing: webpack@^4.0.0, required by grunt-webpack@4.0.2
```
| software         | version
| ---------------- | -------
| webpack          |  5.2.0
| grunt-webpack    | 4.0.2
| grunt            | 1.3.0
| node             | 14.2.0
| npm              | 6.14.5
| Operating System | Windows 10

**Comment by bonesoul** [comment]
same issue here with peer dep

**Comment by lhtdesignde** [comment]
same here

**Comment by alexander-akait** [comment]
@danez friendly ping

**Comment by lhtdesignde** [comment]
looks like they fixed it here: https://github.com/webpack/webpack-cli/issues/1918

**Comment by lhtdesignde** [comment]
they did fix it for the cli but seems like grunt-webpack might need to still get that. not sure what to replace watch:true with. If I remove it as suggested the watch is not working.

**Comment by alexander-akait** [comment]
You can remove `watch: true` from the configuration

**Comment by alexander-akait** [comment]
Error is some misleading, it should be `No need to set `watch: true` when you run watch`

**Comment by lhtdesignde** [comment]
ya but if I do that it doesn't work with the watching.

**Comment by alexander-akait** [comment]
How you run command?

**Comment by lhtdesignde** [comment]
I have 
```
watch: true,
keepalive: true 
```

and i get the deprecation warning. But it does watch when I run the task and updates when I change a file. 
When i remove `watch: true`, the warning is gone but it does not watch anymore.

**Comment by lhtdesignde** [comment]
I run `grunt webpack:devwatch`

**Comment by lhtdesignde** [comment]
The whole task:
```
      devwatch: {
        mode: 'development',
        entry: {
          bundle: './<%= paths.src %>/javascripts/react/containers/Root'
        },
        output: {
          path: path.join(__dirname, '<%= paths.dist %>/javascripts'),
          filename: '[name].js',
          chunkFilename: '[name]-chunk.js',
          publicPath: '/intl/javascripts/'
        },
        plugins: [
          new WebpackManifestPlugin({
            fileName: '../../../.js-names.json',
            filter: (file) => !file.path.match(/\.map$|\d-chunk/)
          })
        ],
        devtool: 'cheap-module-source-map',
        optimization: {
          nodeEnv: 'development',
          mergeDuplicateChunks: true,
          removeEmptyChunks: true,
          concatenateModules: true,
          runtimeChunk: 'single',
          chunkIds: 'total-size',
          moduleIds: 'size',
          splitChunks: {
            chunks: 'all',
            cacheGroups: {
              defaultVendors: {
                name: 'vendor',
                test: /[\\/]node_modules[\\/]/,
                chunks: 'initial',
                reuseExistingChunk: true
              }
            }
          }
        },
        resolve: webpackResolution,
        module: {
          rules: webpackRules
        },
        performance: {
          hints: false
        },
        watch: true, 
        keepalive: true
      }
```

**Comment by alexander-akait** [comment]
Weird, based on source core https://github.com/webpack-contrib/grunt-webpack/blob/master/tasks/webpack.js#L106, you can safely remove `watch` from `webpack.config.js` and use `watch` as option

**Comment by lhtdesignde** [comment]
ahaa so i need to add watchOptions to trigger it instead maybe?

**Comment by alexander-akait** [comment]
`watchOptions` is only for how watch should work, grunt has options on tasks level

**Comment by lhtdesignde** [comment]
yes. how do I use an option with grunt-webpack? If I do grunt `webpack:devwatch --watch` that also doesn't work. so I would need to attach it somehow else?

**Comment by alexander-akait** [comment]
oh, I see, yes, we need to fix it, should be easy, just always set `callback` for any webpack run

**Comment by epx-nathan** [comment]
@alexander-akait Apologies if this is a silly question, but I assume from your comment above that this is something that needs to be handled in this package? (i.e. always setting a `callback`.) Or is it something users can take care of on our ends via some grunt setting?

**Comment by alexander-akait** [comment]
@epx-nathan Do you still have warning? Can you provide simple example?

**Comment by epx-nathan** [comment]
@alexander-akait Looks like @danez has created a PR with a fix! I can't provide a full simple code example but the packages I'm using are:
- grunt v1.3.0
- grunt-webpack v4.0.2
- webpack v5.33.2
- webpack-cli v4.6.0

My grunt file just imports my webpack config and then refers to it in this way:

![Screen Shot 2021-04-18 at 8 25 03 AM](https://user-images.githubusercontent.com/55513121/115147219-950cb380-a01f-11eb-8e9a-517e68a9b009.png)

And my webpack file has watch defined as true:

![Screen Shot 2021-04-18 at 8 25 35 AM](https://user-images.githubusercontent.com/55513121/115147229-a786ed00-a01f-11eb-8c55-791d698ae646.png)

**Comment by epx-nathan** [comment]
Just responding to let you all know that this did fix my issue. Thanks so much for the quick turnaround, really appreciated!
