### ISSUE TITLE
Add webpack-dev-server example

### ISSUE THREAD

**Issue by ladas-larry** [webpack-contrib/grunt-webpack#54]
Usage of `webpack-dev-server` command is missing.

**Comment by dickeylth** [comment]
+1

**Comment by carlosrberto** [comment]
+1

**Comment by carlosrberto** [comment]
I'm having issues trying to use the dev-server setup

```javascript
webpack: {
	// webpack setup
},

"webpack-dev-server": {
	// dev server setup
}
```

when I start the task `webpack` it runs the  `webpack-dev-server` task

**Comment by onury** [comment]
+1

**Comment by adikari** [comment]
+1

**Comment by adikari** [comment]
You might find this helpful. https://github.com/webpack/webpack-with-common-libs/blob/master/Gruntfile.js

**Comment by y0n1** [comment]
(+1)

**Comment by axten** [comment]
+1
