### ISSUE TITLE
Grunt task fails with keepalive & watch, when there is a syntax error.

### ISSUE THREAD

**Issue by Jmeyering** [webpack-contrib/grunt-webpack#65]
When using the keepalive & watch options, if there is a syntax error in one of the modules, the task fails out 

```
Warning: Task "webpack:dev-build:keepalive" failed. Use --force to continue.
```

I've tried running the task with the force option, but we just keep dying.

This is somewhat of a deal break for active development environments, where syntax errors are pretty common

Am I doing something wrong here?

Here is my webpack grunt config. I use load-grunt-configs so its in yaml format.

```
options:
    cache: true
    entry: <%= meta.jsAssets %>/<%= meta.mainJs %>
    output:
        path: <%= meta.jsPublic %>
        filename: <%= meta.mainJs %>
        sourceMapFilename: "[file].map"
    resolve:
        modulesDirectories:
            - <%= meta.jsAssets %>
            - <%= meta.nodeModulesDir %>
build:
    debug: false

dev-build:
    devtool: sourcemap
    debug: true
    watch: true
    keepalive: true
```

**Comment by nickstanish** [comment]
I'm having the same issue

**Comment by nickstanish** [comment]
@Jmeyering Try setting `failOnError: false`

**Comment by MichaelSitter** [comment]
Had the same issue. Not sure about `failOnError`, but the grunt `--force` flag worked for me

**Comment by theoephraim** [comment]
Any news here? `failOnError` did not seem to work

**Comment by Jmeyering** [comment]
I gave up on this plugin, and just use the exec grunt plugin to delegate to the webpack binary directly.

**Comment by sebastienbarre** [comment]
Unfortunately it seems this plugin [is passing a `failOnError` option](https://github.com/webpack/grunt-webpack/blob/master/tasks/webpack.js#L29) that is now rejected by Webpack itself:
```
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'failOnError'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
```
@sokra?

**Comment by danez** [comment]
@sebastienbarre I assume this is webpack 2?

**Comment by sebastienbarre** [comment]
@danez This is, yes.

**Comment by danez** [comment]
This will be fixed in the next release.
