### ISSUE TITLE
"someName" docs

### ISSUE THREAD

**Issue by acthp** [webpack-contrib/grunt-webpack#71]
What is "someName"? I don't understand what this property name is for, as shown in the example config.

**Comment by mingyuan-xia** [comment]
it is an arbitrary name you assigned as the Grunt task name.
take a look at this: http://gruntjs.com/getting-started#an-example-gruntfile
sometimes you need multiple tasks with the webpack plugin
with "someName" the actual task name is `grunt webpack:someName`, and with "anotherName" you have `grunt webpack:anotherName`

**Comment by kiwenlau** [comment]
Actually, I don't want to specify the name. How can I remove it?

**Comment by mingyuan-xia** [comment]
If you only have one config and being the default, then calling `grunt webpack` will go to that one. The name(s) are only necessary when you have more than one webpack tasks, e.g., one for dev, one for production and one for hot watch.
