### ISSUE TITLE
Using grunt-webpack breaks webpack plugin behaviour

### ISSUE THREAD

**Issue by msrose** [webpack-contrib/grunt-webpack#97]
In this specific case I'm using the [webpack manifest plugin](https://www.npmjs.com/package/webpack-manifest-plugin); the output from grunt-webpack is different from simply running webpack:

### Webpack/Grunt Configuration

webpack.config.js
```js
var ManifestPlugin = require('webpack-manifest-plugin');

var manifestCache = {};

module.exports = [{
    entry: {
        one: './one.js',
    },
    output: {
        filename: '[name].[chunkhash].js'
    },
    plugins: [
        new ManifestPlugin({
            cache: manifestCache
        })
    ]
}, {
    entry: {
        two: './two.js',
    },
    output: {
        filename: '[name].[chunkhash].js'
    },
    plugins: [
        new ManifestPlugin({
            cache: manifestCache
        })
    ]
}];
```

gruntfile.js
```js
module.exports = function(grunt) {
    grunt.initConfig({
        webpack: {
            build: require('./webpack.config')
        }
    });
    grunt.loadNpmTasks('grunt-webpack');
};
```

one.js
```js
console.log('one');
```

two.js
```js
console.log('two');
```
### Expected Behavior

I would expect both `./node_modules/.bin/webpack` and `grunt webpack` to produce the same webpack manifest file:
```json
{
  "one.js": "one.8661e1cedb3d3c745aca.js",
  "two.js": "two.c2a72e68ee30405281ca.js"
}
```

### Current Behavior

Running `grunt webpack` produces an incorrect manifest file:

```json
{
  "two.js": "two.c2a72e68ee30405281ca.js"
}
```

### Possible Solution

After looking through the code, I'm quite sure that using `lodash.mergeWith` results in grunt-webpack creating a deep copy of the webpack config passed to it; therefore, the cache option used by webpack-manifest-plugin doesn't behave correctly, since the cache object is copied as opposed to persisting as the same object as required.

### Context

I came across this when adding multiple compile steps to a webpack config that was already using the manifest plugin. It seemed that the manifest plugin wasn't working as described, but finally I narrowed it down to only occurring when using grunt.

### My Environment
```
Σ node -v
v4.5.0
Σ npm -v
2.15.9
Σ npm ls --depth=0
├── grunt@1.0.1
├── grunt-webpack@1.0.18
├── webpack@1.13.3
└── webpack-manifest-plugin@1.1.0
```
Tested on Mac OS but also experienced on Ubuntu 16.04.

fyi @captbaritone

**Comment by danez** [comment]
Thanks for the report, there are multiple issues with loading configurations, especially with loaders. As you correctly noticed it is because of the merge, but also because we load the config with grunt, which also breaks some edge cases.

I want to look into if there is a way to load the complete config "by hand" (without grunt preprocessing it) and then It should be possible also to figure out this problem.
